local-phone-apps = ApplicationsProvider \
                   BackupRestoreConfirmation \
                   Bluetooth \
                   CertInstaller \
                   DefaultContainerService \
                   DrmProvider \
                   Galaxy4 \
                   GalaxyNoteSettings \
                   Gallery2 \
                   HoloSpiralWallpaper \
                   HTMLViewer \
                   InputDevices \
                   KeyChain \
                   LiveWallpapers \
                   LiveWallpapersPicker \
                   MagicSmokeWallpapers \
                   MediaProvider \
                   MusicFX \
                   NoiseField \
                   PhaseBeam \
                   PicoTts \
                   SamsungServiceMode \
                   SettingsProvider \
                   SharedStorageBackup \
				   Stk \
                   TvOut \
                   UserDictionaryProvider \
                   VideoEditor \
                   VisualizationWallpapers \
                   VoiceDialer \
                   WAPPushManager
