#!/system/bin/sh
#
# thor2002ro module loader 2000
MODULES_PATH=/system/lib/modules/opt

cd $MODULES_PATH
KERNMODS=$(find -name "*.ko")

#dependencies
insmod sunrpc.ko
insmod lockd.ko
insmod auth_rpcgss.ko
insmod nfs_acl.ko

for i in $KERNMODS ; do
     insmod $i
done

exit 0
